version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - "./app:/app:z"
    command: "npm run dev"
    ports:
      - "8080:8080"
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile:z"
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
