version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - "./app:/app:z"
    command: bash -c 'sleep 3 && npm start'
    ports:
      - "8080:8080"
    depends_on:
      - db

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile:z"
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: project1
      POSTGRES_PASSWORD: postgres

volumes:
  caddy_data:
  caddy_config:
